#!/bin/sh
lock() {
    i3lock -c 000000 -e -f -d -I 10
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
