#!/bin/sh
lock() {
    #setxkbmap us -option grp:alt_shift_toggle
    #i3lock -c 000000 -e -f -d -I 10
    #setxkbmap us,il -option grp:alt_shift_toggle
echo "no lock"
}
on_shutdown() {
    killall -q -9 cmst || true
    killall -q -9 clementine || true
}
case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
