#!/bin/bash

apps=(
	"org.mpris.MediaPlayer2.QMPlay2"
	"org.mpris.MediaPlayer2.clementine"
)
mapfile -t tmp < <(busctl --user list | cut "-d " -f1 | grep -F org.mpris.MediaPlayer2)
apps+=("${tmp[@]}")

case "$1" in
	stop)
		for app in "${apps[@]}"; do
			busctl --user call "${app}" /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player Stop
		done
		;;
	pause)
		for app in "${apps[@]}"; do
			busctl --user call "${app}" /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player Pause
		done
		;;
	playpause)
		selected="${apps[0]}"
		for app in "${apps[@]}"; do
            status="$(busctl --user get-property "${app}" /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player PlaybackStatus)"
            if [[ 's "Paused"' = "${status}" ]] || [[ 's "Playing"' = "${status}" ]]; then
				selected="${app}"
				break
			fi
		done
		busctl --user call "${selected}" /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player PlayPause
		;;
	play)
		selected="${apps[0]}"
		for app in "${apps[@]}"; do
            if [[ 's "Paused"' = $(busctl --user get-property "${app}" /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player PlaybackStatus) ]]; then
				selected="${app}"
				break
			fi
		done
		busctl --user call "${selected}" /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player Play
		;;
	next)
		selected="${apps[0]}"
		for app in "${apps[@]}"; do
			if [ Playing = $(qdbus "${app}" /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlaybackStatus) ]; then
				selected="${app}"
				break
			fi
		done
        if [ -z ${selected} ]; then for app in "${apps[@]}"; do
			if [ Paused = $(qdbus "${app}" /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlaybackStatus) ]; then
				selected="${app}"
				break
			fi
		done; fi
		qdbus "${selected}" /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
		;;
	prev)
		selected="${apps[0]}"
		for app in "${apps[@]}"; do
			if [ Playing = $(qdbus "${app}" /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlaybackStatus) ]; then
				selected="${app}"
				break
			fi
		done
        if [ -z ${selected} ]; then for app in "${apps[@]}"; do
			if [ Paused = $(qdbus "${app}" /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlaybackStatus) ]; then
				selected="${app}"
				break
			fi
		done; fi
		qdbus "${selected}" /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous
		;;
esac
