#!/bin/sh
DIR=/home/arthur/Pictures/screenshot
mkdir -p $DIR
FILE="$DIR/$(date +%F-%T).jpg"

case "$1" in
    full)
        maim "$FILE"
        ;;
    window)
        maim -i $(xdotool getactivewindow) "$FILE"
        ;;
    *)
        echo "Usage: $0 {full|window}"
        exit 2
esac

exit 0
