#!/usr/bin/env python

import json
from sys import argv
from urllib import request
from pkg_resources import parse_version


def versions(pkg_name):
    url = f'https://pypi.python.org/pypi/{pkg_name}/json'
    releases = json.loads(request.urlopen(url).read())['releases']
    return sorted(releases, key=parse_version, reverse=True)


if __name__ == '__main__':
    if argv[1][0] == '-':
        pkgs = argv[2:]
        cnt = -int(argv[1])
    else:
        pkgs = argv[1:]
        cnt = None

    for pkg_name in pkgs:
        releases = versions(pkg_name)
        print(pkg_name, ':', releases[0:cnt])
