#
# ~/.bashrc
#


# If not running interactively, don't do anything
[[ $- != *i* ]] && return

source /etc/profile
export HISTCONTROL="$HISTCONTROL erasedups:ignoreboth"

alias gksu='lxsu'
alias gksudo='lxsudo'
alias curl='curl -L'
alias vimview='vim -R'
alias vmless='vim -u ~/.less.vimrc -'
alias xclip='xclip -selection clipboard'
alias protect-file='sudo chattr +i'
alias unprotect-file='sudo chattr -i'
alias notify='sudo -u arthur notify-send'
alias htop='echo-title htop && htop'
alias ncdu='echo-title ncdu && ncdu'

export TERMINAL=qterminal
#export CPPFLAGS="-D_FORTIFY_SOURCE=2"
if [ $EUID != 0 ] && [ $EUID != 250 ]; then
    export CFLAGS="-march=native -mtune=native -O2 -pipe"
    export CXXFLAGS="-march=native -mtune=native -O2 -pipe"
    export LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro"
    export MAKEFLAGS="-j4"
else
    unset MAKEFLAGS CFLAGS CXXFLAGS LDFLAGS
fi

update-system () {
    ( emerge --sync && emerge -atuDUN @world $@ && smart-live-rebuild -- $@ )
}

clean-system() {
    emerge --depclean -a --with-bdeps\=n
}

echo-title() {
    echo -e '\033]2;'"$@"'\007'
}

[[ $- = *i* ]] && source /home/arthur/dev/liquidprompt/liquidprompt

